### ISSUE TITLE
Offline use of app should provide feedback to user

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/forsta-web-messenger#320]
When using the mobile app, there is no user feedback about being offline.  A user can type in a message and think that they "sent" it.  If they notice the exclamation point that it is offline, they don't have the opportunity to "try again".

A couple ideas on how to address this:
1. Have a visible message saying "Not sent" like you see on iMessage
2. Allow to "Try Again"

Or...
Grey out "Send" button if user is offline so they don't have the option to hit Send

**Comment by mayfield** [comment]
Messages are now resent when an error (of any kind occurs).  See #262
