### ISSUE TITLE
"Edit distribution" does not auto populate users

### ISSUE THREAD

**Issue by ultrabrad123** [ForstaLabs/forsta-web-messenger#324]
"Edit Distribution" in messenger fails to auto-populate. When adding to distribution one must remember other users entire @.  

- Mac OS, Safari, Chrome, IOS, Firefox.

The screenshot is the input that doesn't autopopulate.

<img width="1237" alt="Screen Shot 2019-10-16 at 11 47 39 AM" src="https://user-images.githubusercontent.com/55554257/66944892-4dacfd80-f00b-11e9-9505-d3e8e45f1c0d.png">

**Comment by mayfield** [comment]
See #275
