### ISSUE TITLE
Remove deprecated signin page

### ISSUE THREAD

**Issue by mayfield** [ForstaLabs/forsta-web-messenger#338]
atlas-ui does signin now.

**Comment by rosew** [comment]
@mcavoybn  - what were the technical reasons why we moved away from using  /@signin

@mayfield  - what issues do you see with the current way compared to the /@signin that makes you prefer /@signin

**Comment by mayfield** [comment]
It's too late.  Highlander defense.  I'll remove this one.

**Comment by mcavoybn** [comment]
> what were the technical reasons why we moved away from using /@signin

Technical reason here:
https://github.com/ForstaLabs/atlas-ui/issues/585

I also think it makes more sense to use a login page that feels similar to the dashboard.
